### ISSUE TITLE
关于Temperature的问题想向您请教，期盼回复

### ISSUE THREAD

**Issue by Ljiaqii** [kaijieshi7/Dynamic-convolution-Pytorch#16]
作者您好，感谢您对论文的复现！

程序中关于温度问题我还不太明白，期待您的回复：
1.不同的温度值对于模型的训练有什么影响呢？在程序的哪个部分可以体现呢？
2.如果想要使训练温度保持恒定，即不使用temperature annealing，在程序中需要做哪些改动呢？

再次表示感谢！祝您一切顺利！！

**Comment by Zhenyu-040314** [comment]
当T=1时，就是普通的softmax变换。这里令T>1，就得到了软化的softmax。（这个很好理解，除以一个比1大的数，相当于被squash了，线性的sqush被指数放大，差距就不会这么大了。希望能帮到你

**Comment by Ljiaqii** [comment]
明白啦 谢谢你~
